// admin/src/ui-builder/utils/export-utils.js
import JSZip from "jszip";
import { saveAs } from "file-saver";
import { renderTreeToHTML } from "./node-utils";

/**
 * createPluginPackage
 * inputs:
 * - tree: elements array (root)
 * - meta: { slug, name, author, version, description }
 *
 * outputs: promise that resolves to Blob (zip)
 */
export async function createPluginPackage(tree, meta = {}) {
  const zip = new JSZip();

  const slug = meta.slug || `wpb-plugin-${Date.now()}`;
  const pluginDir = `${slug}`;

  // generate plugin bootstrap
  const pluginPhp = generatePluginPhp(meta);
  zip.file(`${pluginDir}/${slug}.php`, pluginPhp);

  // assets: simple index.html preview and css
  const previewHtml = generatePreviewHtml(renderTreeToHTML(tree), meta);
  zip.file(`${pluginDir}/preview.html`, previewHtml);

  // styles
  const css = "/* Generated styles (empty by default) */\n";
  zip.file(`${pluginDir}/assets/style.css`, css);

  // readme
  const readme = `=== ${meta.name || slug} ===\n\n${meta.description || ""}\n`;
  zip.file(`${pluginDir}/readme.txt`, readme);

  // optionally add serialized JSON of tree
  const json = JSON.stringify({ meta, tree }, null, 2);
  zip.file(`${pluginDir}/data/tree.json`, json);

  const content = await zip.generateAsync({ type: "blob" });
  return content;
}

export async function exportPluginZipAndDownload(tree, meta = {}) {
  const blob = await createPluginPackage(tree, meta);
  saveAs(blob, `${(meta.slug || "wpb-plugin")}.zip`);
}

/* small template functions */
function generatePluginPhp(meta = {}) {
  const name = meta.name || "WP Plugin Builder Export";
  const slug = meta.slug || "wpb-plugin";
  const desc = meta.description || "Generated by WP Plugin Builder";
  const version = meta.version || "1.0.0";
  const author = meta.author || "WPB";

  return `<?php
/**
 * Plugin Name: ${escapePhp(name)}
 * Description: ${escapePhp(desc)}
 * Version: ${version}
 * Author: ${escapePhp(author)}
 */

if (!defined('ABSPATH')) exit;

// Simple preview page registration
add_action('admin_menu', function() {
  add_menu_page('${escapePhp(name)}', '${escapePhp(name)}', 'manage_options', '${slug}-preview', function() {
    echo '<iframe style="width:100%;height:100vh;border:none" src="'.plugins_url("preview.html", __FILE__).'"></iframe>';
  });
});
`;
}

function generatePreviewHtml(bodyHtml, meta = {}) {
  return `<!doctype html>
<html>
<head>
<meta charset="utf-8">
<title>${escapeHtml(meta.name || "Preview")}</title>
<link rel="stylesheet" href="assets/style.css" />
</head>
<body>
<div class="wpb-preview-root">
${bodyHtml}
</div>
</body>
</html>`;
}

function escapePhp(s=''){ return (s+'').replace(/'/g,"\\'"); }
function escapeHtml(s=''){ return (s+'').replace(/</g,'&lt;').replace(/>/g,'&gt;'); }
